[unix_http_server]
file=/home/USER/supervisor/supervisor.sock

[inet_http_server]
port=*:9001

[supervisord]
logfile=/home/USER/supervisor/supervisord.log
pidfile=/home/USER/supervisor/supervisord.pid

[supervisorctl]
serverurl=unix:///home/USER/supervisor/supervisor.sock

[program:prefect_worker]
command=prefect worker start -p default-pool
autorestart=true
autostart=true
stdout_logfile=/home/USER/supervisor/supervisord_stdout.log
stderr_logfile=/home/USER/supervisor/supervisord_stderr.log
