macro:
  provider_path: "./providers/stocks"
  data_root: "/usr/local/xqsim/data"

global:
  meta_dir: "${data_root}/stocks/cc"
  dst_cache_dir: "${data_root}/stocks/cc"
  output_cache_dir: "${data_root}/stocks/cc_update"
  build: true

meta_updater: "${provider_path}/meta_updater.py"

build:
  base: "${provider_path}/config_production.yml"

client:
  - "192.168.1.69"

ut:
  command: "/opt/conda/envs/conda_env/bin/python /home/michael/xqsim_tools/ut/ut_run.py"
  result_path: "/tmp/ut/result.log"
