macro:
  provider_path: "../../providers"

global:
  meta_dir: "../../providers/cc"
  dst_cache_dir: "../../providers/cc"
  output_cache_dir: "${provider_path}/cc_update"
  build: true

meta_updater: "${provider_path}/meta_updater.py"

build:
  base: "${provider_path}/config_debug.yml"
