macro:
  provider_path: "./providers/stocks"
  data_root: "/usr/local/xqsim/data"

global:
  meta_dir: "${data_root}/stocks/cc"
  dst_cache_dir: "${data_root}/stocks/cc"
  output_cache_dir: "${data_root}/stocks/cc_update_debug"
  build: true

meta_updater: "${provider_path}/DataProviderMetaUpdater.py"

build:
  base: "${provider_path}/config_debug.yml"
