from qsim.alpha_base import *


def main():
    # dr = init_dr(meta_dir=r"E:\CC", begin_date=20180110, end_date=20201231, back_days=5, data_limit=10000000)
    # dr = init_dr(meta_dir="/fast/szhong/cc", begin_date=20190101, end_date=20191231, back_days=0, data_limit=0, cache_list=["/fast/szhong/cc"])
    dr = init_dr(meta_dir="/nfs/share/cc", begin_date=20190101, end_date=20191231, back_days=0, data_limit=0, cache_list=[])

    log_info("begin")
    print(dr.get_data("open")[dr.meta.begin_di][0][10])
    print(dr.get_data("close")[dr.meta.begin_di][0][10])
    print(dr.get_data("open")[dr.meta.begin_di][1][10])
    print(dr.get_data("close")[dr.meta.begin_di][1][10])
    # print(dr.get_data("amount2")[dr.meta.begin_di][8][10])
    # print(dr.get_data("amount3")[dr.meta.begin_di][8][10])
    dr.get_data("ask10_close")
    dr.get_data("ask10_high")
    dr.get_data("ask10_low")
    dr.get_data("ask10_mean")
    dr.get_data("ask10_open")
    dr.get_data("ask5_close")
    dr.get_data("ask5_high")
    dr.get_data("ask5_low")
    dr.get_data("ask5_mean")

    dr.get_data("ask5_open")
    dr.get_data("ask_close")
    dr.get_data("ask_high")
    dr.get_data("ask_low")
    dr.get_data("ask_mean")
    dr.get_data("ask_open")
    dr.get_data("ask_price_close")
    dr.get_data("ask_price_high")
    dr.get_data("ask_price_low")
    dr.get_data("ask_price_mean")
    # dr.get_data("ask_price_open")
    # dr.get_data("avg_ask_close")
    # dr.get_data("avg_ask_high")
    # dr.get_data("avg_ask_low")
    # dr.get_data("avg_ask_mean")
    # dr.get_data("avg_ask_open")
    # dr.get_data("avg_bid_close")
    # dr.get_data("avg_bid_high")
    # dr.get_data("avg_bid_low")
    # dr.get_data("avg_bid_mean")
    # dr.get_data("avg_bid_open")

    log_info("finish")

if __name__ == '__main__':
    main()
