macro:
  provider_dir: "${config}"

global:
  meta_dir: "${xqsim_data}/stocks/cc"
  output_cache_dir: "${xqsim_data}/stocks/cc_update_debug"
  begin_date: "20130101"
  end_date: "20211231"
  build: true

provider:
  local:
    mysql_config: "mysql.json"
#  KLine:
#    file_path: "${provider_dir}/DataProviderKline.py"
#  Universe:
#    file_path: "${provider_dir}/DataProviderUniverse.py"
#  Barra:
#    file_path: "${provider_dir}/DataProviderBarra.py"
#  Industry:
#    file_path: "${provider_dir}/DataProviderIndustry.py"
#  IndexKLine:
#    file_path: "${provider_dir}/DataProviderIndexKline.py"
#  ComponentWeight:
#    file_path: "${provider_dir}/DataProviderComponentWeight.py"
#  CiticsIndex:
#    file_path: "${provider_dir}/DataProviderCiticsIndexKline.py"

## intra day
#  KLineIntraday:
#    file_path: "${provider_dir}/DataProviderKlineIntraday.py"
#  IndexKLineIntraday:
#    file_path: "${provider_dir}/DataProviderIndexKlineIntraday.py"

## wind daily
#  ASHAREMONEYFLOW:
#    file_path: "${provider_dir}/DataProviderWindCommon.py"
#    abbr: "mf"
#  ASHAREEODDERIVATIVEINDICATOR:
#    file_path: "${provider_dir}/DataProviderWindCommon.py"
#    abbr: "dv"
#  SHSCCHANNELHOLDINGS:
#    file_path: "${provider_dir}/DataProviderWindCommon.py"
#    abbr: "shsc"
#    code_find: true

## financial_statement
  ASHAREINCOME:
    file_path: "${provider_dir}/DataProviderWindFinancialStatement.py"
    abbr: "ic"
  ASHAREBALANCESHEET:
    file_path: "${provider_dir}/DataProviderWindFinancialStatement.py"
    abbr: "bs"
  ASHARECASHFLOW:
    file_path: "${provider_dir}/DataProviderWindFinancialStatement.py"
    abbr: "cf"



