macro:
  provider_dir: "${config}"

global:
  meta_dir: "${xqsim_data}/stocks/cc"
  output_cache_dir: "${xqsim_data}/stocks/cc_single"
  begin_date: "20130101"
  end_date: "TODAY"
  build: true

provider:

  KLine:
    file_path: "${provider_dir}/DataProviderKline.py"

  Universe:
    file_path: "${provider_dir}/DataProviderUniverse.py"
## financial_simple
#  ASHAREANNFINANCIALINDICATOR:
#    file_path: "${provider_dir}/DataProviderWindFinancialSimple.py"
#  ASHAREAUDITOPINION:
#    file_path: "${provider_dir}/DataProviderWindFinancialSimple.py"
#  ASHAREFINANCIALINDICATOR:
#    file_path: "${provider_dir}/DataProviderWindFinancialSimple.py"
#  ASHAREISSUINGDATEPREDICT:
#    file_path: "${provider_dir}/DataProviderWindFinancialSimple.py"
#    extra:
#      - S_STM_PREDICT_ISSUINGDATE
#      - S_STM_ACTUAL_ISSUINGDATE
#      - S_STM_CORRECT_NUM
#      - S_STM_CORRECT_ISSUINGDATE
#  ASHAREPROFITEXPRESS:
#    file_path: "${provider_dir}/DataProviderWindFinancialSimple.py"
#    actual_ann_dt: "ACTUAL_ANN_DT"
#  ASHAREPROFITNOTICE:
#    file_path: "${provider_dir}/DataProviderWindFinancialSimple.py"
#    ann_dt: "S_PROFITNOTICE_DATE"
#    report_period: "S_PROFITNOTICE_PERIOD"
#    extra:
#      - S_PROFITNOTICE_SIGNCHANGE
#      - S_PROFITNOTICE_FIRSTANNDATE
#
#  ASHAREACCOUNTINGCHANGE:
#    file_path: "${provider_dir}/DataProviderWindFinancialSimple.py"
#    comp: true
#    report_period: "BE_AFFECTED_REPORT_PERIOD"
#    ann_dt: "ANN_DATE"
