[unix_http_server]
file=/home/USER/supervisor/supervisor.sock   ;UNIX socket 文件，supervisorctl 会使用

[inet_http_server]         ;HTTP服务器，提供web管理界面
port=*:9001        ;Web管理后台运行的IP和端口，如果开放到公网，需要注意安全性

[supervisord]
logfile=/home/USER/supervisor/supervisord.log ;日志文件，默认是 $CWD/supervisord.log
pidfile=/home/USER/supervisor/supervisord.pid ;pid 文件

[supervisorctl]
serverurl=unix:///home/USER/supervisor/supervisor.sock ;通过UNIX socket连接supervisord，路径与unix_http_server部分的file一致

[program:prefect_agent]
command=prefect agent local start
autorestart=true
autostart=true
stdout_logfile=/home/USER/supervisor/supervisord_stdout.log
stderr_logfile=/home/USER/supervisor/supervisord_stderr.log